// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Execute one command against the shared context.
	 * 
	 *  Errors are flattened to [`CommandErrorPayload`] (`{ code, message }`) because
	 *  `CommandError` wraps `FocuserError`, which has no TypeScript representation.
	 *  The frontend branches on `code`, never on `message`.
	 *  `(async)` on a sync function puts it on Tauri's blocking thread pool.
	 *  Without it the default is the event-loop thread, and a slow command — icons
	 *  especially — freezes the window.
	 */
	runCommand: (command: Command) => typedError<CommandResult, CommandErrorPayload>(__TAURI_INVOKE("run_command", { command })),
};

/* Types */
/**  A user-configured daily time budget for a domain or app. */
export type Allowance = {
	id: string,
	target: AllowanceMatch,
	daily_limit_secs: number,
	/**
	 *  If true, only count time when the tab/app is actively focused.
	 *  If false, count as long as it's open.
	 */
	strict_mode: boolean,
	enabled: boolean,
	created_at: string,
};

/**  What an allowance targets: a domain or an application. */
export type AllowanceMatch = 
/**  A domain (matches the domain itself and any subdomain). */
{ kind: "Domain"; value: string } | 
/**  An app matched by executable name (e.g., "steam.exe"). */
{ kind: "AppExecutable"; value: string };

/**
 *  An allowance crossing a threshold. Mirrors `focuser_core`'s internal type,
 *  which is not `specta::Type`.
 */
export type AllowanceNotificationDto = {
	allowance_id: string,
	target: string,
	kind: string,
	used_secs: number,
	limit_secs: number,
};

export type AllowancePeriod = "PerHour" | "PerDay";

/**  A snapshot of an allowance with today's usage, for the UI. */
export type AllowanceStatus = {
	allowance: Allowance,
	used_today_secs: number,
	/**  `remaining = max(daily_limit - used, 0)`. */
	remaining_secs: number,
	/**  True once `used_today_secs >= daily_limit_secs`. */
	exhausted: boolean,
};

/**  One day's usage against an allowance. */
export type AllowanceUsageEntry = {
	date: string,
	used_secs: number,
};

/**  One application rule's icon. */
export type AppIcon = {
	/**
	 *  Echoed back so the caller can match icons to rows without relying on
	 *  the order it sent them in.
	 */
	target: string,
	/**
	 *  A `data:image/png;base64,…` URI, or `None` when the rule does not name
	 *  a program we can find — a window title, or software since uninstalled.
	 */
	data_uri: string | null,
};

export type AppMatchType = 
/**  Match by executable name (e.g., "steam.exe") */
({ ExecutableName: string }) & { BundleId?: never; ExecutablePath?: never; WindowTitle?: never } | 
/**  Match by full path (e.g., "C:\\Program Files\\Steam\\steam.exe") */
({ ExecutablePath: string }) & { BundleId?: never; ExecutableName?: never; WindowTitle?: never } | 
/**  Match by window title substring */
({ WindowTitle: string }) & { BundleId?: never; ExecutableName?: never; ExecutablePath?: never } | 
/**  macOS bundle ID (e.g., "com.apple.Safari") */
({ BundleId: string }) & { ExecutableName?: never; ExecutablePath?: never; WindowTitle?: never };

export type AppRule = {
	id: string,
	match_type: AppMatchType,
	enabled: boolean,
};

/**  A named collection of blocking rules. */
export type BlockList = {
	id: string,
	name: string,
	enabled: boolean,
	websites: WebsiteRule[],
	applications: AppRule[],
	exceptions: ExceptionRule[],
	lock: Lock | null,
	protection: Protection | null,
	schedule: Schedule | null,
	breaks: BreakConfig | null,
	created_at: string,
	updated_at: string,
};

/**  A single block event with precise timestamp (for timeline charts). */
export type BlockedEvent = {
	domain_or_app: string,
	timestamp: string,
};

/**
 *  Whether blocking is actually taking effect, for the UI to warn about.
 * 
 *  Focuser blocks websites two ways: the browser extension, and the OS hosts
 *  file. The hosts path needs administrator or root, and when the write fails
 *  there is nothing on screen to say so — the user sees rules that look armed
 *  and sites that still load. This is what makes that visible.
 */
export type BlockingHealth = {
	/**  Block lists that should be blocking at this moment. */
	active_lists: number,
	/**  An extension has checked in recently, so it is enforcing rules. */
	extension_connected: boolean,
	/**  The hosts file can be written — i.e. we have the privileges for it. */
	hosts_writable: boolean,
	/**
	 *  A keyword, wildcard or URL-path rule is active. Only the extension can
	 *  enforce those; a hosts file has no way to express them.
	 */
	extension_only_rules: boolean,
};

export type BreakConfig = 
/**  Pomodoro-style: work for X minutes, break for Y minutes. */
({ Pomodoro: {
	work_minutes: number,
	break_minutes: number,
	long_break_minutes: number,
	sessions_before_long_break: number,
} }) & { Allowance?: never } | 
/**  Allowance: X minutes of access per day/hour, tracked by activity. */
({ Allowance: {
	allowed_minutes: number,
	period: AllowancePeriod,
	/**  If true, only counts time when the blocked site/app is in focus. */
	track_active_only: boolean,
} }) & { Pomodoro?: never };

/**  One known browser and whether Focuser can see it. */
export type BrowserStatus = {
	browser: string,
	display_name: string,
	running: boolean,
	extension_connected: boolean,
	/**  Where to install the extension for this browser. */
	store_url: string,
	/**  Short name for launching this browser at a URL. */
	launch_name: string,
};

/**
 *  One application action.
 * 
 *  Adjacently tagged so the wire form is `{"cmd": "...", "args": {...}}` — stable,
 *  self-describing, and a clean discriminated union in TypeScript.
 */
export type Command = 
/**  All block lists, with their rules. */
{ cmd: "list_block_lists" } | 
/**  Create an empty block list. Returns the created list. */
{ cmd: "create_block_list"; args: {
	name: string,
} } | 
/**
 *  Replace a block list wholesale.
 * 
 *  Takes a real [`BlockList`], not the JSON string the old
 *  `update_block_list(list_json: String)` accepted.
 */
{ cmd: "update_block_list"; args: {
	list: BlockList,
} } | 
/**  Delete a block list and re-sync the hosts file. */
{ cmd: "delete_block_list"; args: {
	id: string,
} } | 
/**  Enable or disable a block list. */
{ cmd: "toggle_block_list"; args: {
	id: string,
	enabled: boolean,
} } | 
/**
 *  Add a website rule. The match type carries its own value, so there is no
 *  separate stringly-typed `rule_type` to get wrong.
 */
{ cmd: "add_website_rule"; args: {
	list_id: string,
	rule: WebsiteMatchType,
} } | 
/**  Remove a website rule. Errors if the rule is not in the list. */
{ cmd: "remove_website_rule"; args: {
	list_id: string,
	rule_id: string,
} } | 
/**
 *  Add many website rules of one kind at once, skipping blanks, comment
 *  lines, and values already present. Returns how many were added.
 */
{ cmd: "bulk_import_websites"; args: {
	list_id: string,
	values: string[],
	kind: WebsiteRuleKind,
} } | 
/**  Remove every website rule from every unprotected list. */
{ cmd: "clear_all_websites" } | { cmd: "add_app_rule"; args: {
	list_id: string,
	rule: AppMatchType,
} } | 
/**  Remove an app rule. Errors if the rule is not in the list. */
{ cmd: "remove_app_rule"; args: {
	list_id: string,
	rule_id: string,
} } | 
/**  Remove every app rule from every unprotected list. */
{ cmd: "clear_all_apps" } | { cmd: "add_exception"; args: {
	list_id: string,
	exception: ExceptionType,
} } | 
/**  Remove an exception. Errors if it is not in the list. */
{ cmd: "remove_exception"; args: {
	list_id: string,
	exception_id: string,
} } | 
/**
 *  Replace a list's schedule.
 * 
 *  `always_active` clears the schedule entirely, meaning the list blocks at
 *  all times. Slots are real [`TimeSlot`]s — the old command took
 *  `Vec<serde_json::Value>` and hand-parsed `"Mon"`-style day strings,
 *  silently dropping any slot it failed to recognise.
 */
{ cmd: "update_schedule"; args: {
	list_id: string,
	slots: TimeSlot[],
	always_active: boolean,
} } | { cmd: "get_stats"; args: {
	from: string,
	to: string,
} } | { cmd: "get_blocked_events"; args: {
	from: string,
	to: string,
} } | 
/**  Delete all statistics and blocked events. Block lists are preserved. */
{ cmd: "clear_statistics" } | { cmd: "get_stats_retention" } | 
/**
 *  Set the retention window and immediately prune anything older.
 *  Returns the number of rows deleted.
 */
{ cmd: "set_stats_retention"; args: {
	days: number,
} } | { cmd: "enable_protection"; args: {
	list_id: string,
	duration_minutes: number,
	prevent_uninstall: boolean,
	prevent_service_stop: boolean,
	prevent_modification: boolean,
} } | { cmd: "get_protection_status" } | { cmd: "get_setting"; args: {
	key: string,
	default: string | null,
} } | { cmd: "set_setting"; args: {
	key: string,
	value: string,
} } | 
/**  Reset settings to defaults. Block lists and statistics are preserved. */
{ cmd: "reset_settings" } | 
/**  Whether blocking is actually in force right now, and why not if it isn't. */
{ cmd: "get_blocking_health" } | 
/**  Push the current blocked-domain set to the hosts file now. */
{ cmd: "apply_blocks" } | 
/**  Remove Focuser's hosts-file entries. */
{ cmd: "remove_blocks" } | 
/**  Current session, or `None` when nothing is running. */
{ cmd: "pomodoro_status" } | 
/**  The built-in duration presets, in display order. */
{ cmd: "pomodoro_presets" } | { cmd: "pomodoro_start"; args: {
	block_list_id: string,
	config: PomodoroConfig,
} } | 
/**  Returns whether a session was actually paused. */
{ cmd: "pomodoro_pause" } | { cmd: "pomodoro_resume" } | 
/**  Returns whether a phase actually advanced. */
{ cmd: "pomodoro_skip" } | 
/**  Returns whether a session was actually stopped. */
{ cmd: "pomodoro_stop" } | 
/**  Take and clear buffered phase-change / tamper events. */
{ cmd: "pomodoro_drain_events" } | { cmd: "pomodoro_history"; args: {
	days: number,
} } | { cmd: "allowance_list" } | 
/**  The target carries its own kind, so there is no separate `kind: String`. */
{ cmd: "allowance_create"; args: {
	target: AllowanceMatch,
	daily_limit_secs: number,
	strict_mode: boolean,
} } | { cmd: "allowance_update"; args: {
	id: string,
	daily_limit_secs: number,
	strict_mode: boolean,
	enabled: boolean,
} } | { cmd: "allowance_delete"; args: {
	id: string,
} } | 
/**  Zero today's usage for one allowance. */
{ cmd: "allowance_reset_today"; args: {
	id: string,
} } | { cmd: "allowance_drain_notifications" } | { cmd: "allowance_history"; args: {
	id: string,
	days: number,
} } | 
/**
 *  Serialise every block list to a portable JSON document.
 * 
 *  Returns the text rather than writing a file — where it goes is the
 *  frontend's business (a save dialog in the GUI, a path in the CLI).
 */
{ cmd: "export_configuration" } | 
/**
 *  Replace every block list with the contents of an exported document.
 *  Statistics and settings are untouched.
 */
{ cmd: "import_configuration"; args: {
	json: string,
} } | 
/**  Delete block lists, rules, schedules, statistics and settings. */
{ cmd: "delete_all_data" } | 
/**  Would this domain be blocked right now? */
{ cmd: "check_domain"; args: {
	domain: string,
} } | 
/**  Which known browsers are running, and which have the extension. */
{ cmd: "get_browser_status" } | 
/**
 *  Icons for application rules, read from the executables on disk.
 * 
 *  Batched because the caller wants a whole list at once and these are
 *  carried inline; one request per row would be one round trip per row.
 */
{ cmd: "get_app_icons"; args: {
	targets: string[],
} } | { cmd: "app_version" };

/**
 *  The wire form of a failure: `{ "code": ..., "message": ... }`.
 * 
 *  A separate type because [`CommandError`] cannot itself derive `specta::Type` —
 *  its `Core` variant wraps `FocuserError`, which has no TypeScript
 *  representation. This is what crosses the boundary, and what the generated
 *  bindings describe.
 */
export type CommandErrorPayload = {
	/**  Stable identifier for the failure kind. Safe to branch on. */
	code: string,
	/**  Human-readable explanation. Not stable; never branch on it. */
	message: string,
};

/**
 *  The result of a successful [`Command`].
 * 
 *  Deliberately typed — the old command layer returned `serde_json::Value` from
 *  24 of its 55 commands, which meant the frontend hand-decoded shapes that the
 *  compiler never checked.
 */
export type CommandResult = 
/**  Succeeded, nothing to return. */
{ kind: "unit" } | { kind: "block_list"; data: BlockList } | { kind: "block_lists"; data: BlockList[] } | { kind: "website_rule"; data: WebsiteRule } | { kind: "app_rule"; data: AppRule } | { kind: "exception"; data: ExceptionRule } | 
/**  A number of affected items — e.g. rules imported or cleared. */
{ kind: "count"; data: number } | { kind: "stats"; data: UsageStat[] } | { kind: "blocked_events"; data: BlockedEvent[] } | { kind: "protection_status"; data: ProtectionInfo[] } | { kind: "blocking_health"; data: BlockingHealth } | 
/**  A setting value; `None` when unset and no default was supplied. */
{ kind: "setting"; data: string | null } | 
/**  A yes/no outcome — e.g. "was a session actually paused". */
{ kind: "flag"; data: boolean } | 
/**  Current Pomodoro session, or `None` when idle. */
{ kind: "pomodoro_status"; data: PomodoroStatus | null } | { kind: "pomodoro_session"; data: PomodoroSession } | { kind: "pomodoro_events"; data: PomodoroEventDto[] } | { kind: "pomodoro_history"; data: PomodoroHistoryEntry[] } | { kind: "pomodoro_presets"; data: PomodoroPreset[] } | { kind: "allowance"; data: Allowance } | { kind: "allowances"; data: AllowanceStatus[] } | { kind: "allowance_notifications"; data: AllowanceNotificationDto[] } | { kind: "allowance_history"; data: AllowanceUsageEntry[] } | 
/**  Free text — an exported configuration document, or a version string. */
{ kind: "text"; data: string } | { kind: "browser_status"; data: BrowserStatus[] } | { kind: "app_icons"; data: AppIcon[] };

export type ExceptionRule = {
	id: string,
	exception_type: ExceptionType,
	enabled: boolean,
};

export type ExceptionType = 
/**  Allow a specific domain even when other rules would block it */
({ Domain: string }) & { Wildcard?: never } | 
/**  Allow a wildcard pattern */
({ Wildcard: string }) & { Domain?: never } | 
/**  Allow local file:// URLs */
"LocalFiles";

/**  How a block is enforced — determines what it takes to disable it. */
export type Lock = 
/**  Block runs for a fixed duration, cannot be cancelled. */
({ Timer: {
	duration_minutes: number,
	started_at: string | null,
} }) & { Password?: never; RandomText?: never; Until?: never } | 
/**  Must type a long random string to unlock. */
({ RandomText: {
	length: number,
} }) & { Password?: never; Timer?: never; Until?: never } | 
/**  Locked until a specific time. */
({ Until: {
	unlock_at: string,
} }) & { Password?: never; RandomText?: never; Timer?: never } | 
/**  Requires system restart to disable (block re-enables on boot). */
"Restart" | 
/**  Password-protected (hashed). */
({ Password: {
	hash: string,
} }) & { RandomText?: never; Timer?: never; Until?: never } | 
/**  Follows the attached schedule — active during scheduled times. */
"Scheduled";

/**  User-editable configuration for a Pomodoro session. */
export type PomodoroConfig = {
	work_secs: number,
	short_break_secs: number,
	long_break_secs: number,
	cycles_until_long_break: number,
};

/**
 *  A buffered Pomodoro event, in wire form.
 * 
 *  `focuser_app::PomodoroEvent` is the internal type and has no `specta::Type`;
 *  this is its serialisable counterpart.
 */
export type PomodoroEventDto = { kind: "phase_advanced"; to: string; cycle: number } | { kind: "tamper_detected" };

/**  One completed Pomodoro session, for the statistics page. */
export type PomodoroHistoryEntry = {
	started_at: string,
	completed_cycles: number,
	total_work_secs: number,
};

export type PomodoroPhase = "work" | "short_break" | "long_break";

/**
 *  A named starting point for a Pomodoro session.
 * 
 *  The three built-ins are the single source of these numbers. The GUI and the
 *  CLI both read them through [`presets`] instead of restating them, so a
 *  change here reaches every surface at once.
 */
export type PomodoroPreset = {
	/**  Stable identifier — what `--preset` accepts. Never translated. */
	key: string,
	/**  What the user sees. */
	label: string,
	config: PomodoroConfig,
};

/**  An active Pomodoro session. Persisted to DB across restarts. */
export type PomodoroSession = {
	id: string,
	block_list_id: string,
	config: PomodoroConfig,
	current_phase: PomodoroPhase,
	current_cycle: number,
	phase_started_at: string,
	/**
	 *  If Some, the session is paused and this is the remaining time
	 *  when resumed (in seconds).
	 */
	paused_remaining_secs: number | null,
	completed_cycles: number,
	started_at: string,
	/**
	 *  The `enabled` state of the linked block list before this Pomodoro
	 *  session started. Restored when the session ends.
	 */
	prev_enabled: boolean,
};

/**  Snapshot of the Pomodoro state for the UI. */
export type PomodoroStatus = {
	session_id: string,
	block_list_id: string,
	block_list_name: string,
	config: PomodoroConfig,
	current_phase: PomodoroPhase,
	current_cycle: number,
	completed_cycles: number,
	remaining_secs: number,
	phase_duration_secs: number,
	paused: boolean,
	started_at: string,
};

export type Protection = {
	prevent_uninstall: boolean,
	prevent_service_stop: boolean,
	prevent_modification: boolean,
	started_at: string,
	expires_at: string,
};

/**
 *  An active protection window on a block list.
 * 
 *  Replaces the ad-hoc `serde_json::json!` object the old command built.
 */
export type ProtectionInfo = {
	block_list_id: string,
	block_list_name: string,
	prevent_uninstall: boolean,
	prevent_service_stop: boolean,
	prevent_modification: boolean,
	/**
	 *  Exported as a TS `number`; see the note on [`UsageStat`] — seconds can
	 *  never approach the 2^53 precision ceiling.
	 */
	remaining_seconds: number,
	expires_at: string,
};

/**  Weekly recurring schedule. */
export type Schedule = {
	id: string,
	name: string,
	time_slots: TimeSlot[],
	enabled: boolean,
};

/**  A time range on a specific day of the week. */
export type TimeSlot = {
	day: string,
	start: string,
	end: string,
};

export type UsageStat = {
	domain_or_app: string,
	duration_seconds: number,
	blocked_attempts: number,
	date: string,
};

/**  How a website rule matches URLs/domains. */
export type WebsiteMatchType = 
/**  Exact domain match (e.g., "reddit.com" blocks reddit.com and *.reddit.com) */
({ Domain: string }) & { Keyword?: never; UrlPath?: never; Wildcard?: never } | 
/**  Wildcard pattern (e.g., "*.social.*") */
({ Wildcard: string }) & { Domain?: never; Keyword?: never; UrlPath?: never } | 
/**  Keyword anywhere in URL (e.g., "game" blocks any URL containing "game") */
({ Keyword: string }) & { Domain?: never; UrlPath?: never; Wildcard?: never } | 
/**  Exact URL path match (e.g., "reddit.com/r/gaming") */
({ UrlPath: string }) & { Domain?: never; Keyword?: never; Wildcard?: never } | 
/**  Block the entire internet (with exceptions only) */
"EntireInternet";

export type WebsiteRule = {
	id: string,
	match_type: WebsiteMatchType,
	enabled: boolean,
};

/**
 *  A website rule kind *without* its value.
 * 
 *  Needed by bulk import, which supplies one kind and many values. Distinct from
 *  [`WebsiteMatchType`], which always carries its payload.
 */
export type WebsiteRuleKind = "domain" | "keyword" | "wildcard" | "url_path";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

