// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Execute one command against the shared context.
	 * 
	 *  Errors are flattened to [`CommandErrorPayload`] (`{ code, message }`) because
	 *  `CommandError` wraps `FocuserError`, which has no TypeScript representation.
	 *  The frontend branches on `code`, never on `message`.
	 */
	runCommand: (command: Command) => typedError<CommandResult, CommandErrorPayload>(__TAURI_INVOKE("run_command", { command })),
};

/* Types */
export type AllowancePeriod = "PerHour" | "PerDay";

export type AppMatchType = 
/**  Match by executable name (e.g., "steam.exe") */
({ ExecutableName: string }) & { BundleId?: never; ExecutablePath?: never; WindowTitle?: never } | 
/**  Match by full path (e.g., "C:\\Program Files\\Steam\\steam.exe") */
({ ExecutablePath: string }) & { BundleId?: never; ExecutableName?: never; WindowTitle?: never } | 
/**  Match by window title substring */
({ WindowTitle: string }) & { BundleId?: never; ExecutableName?: never; ExecutablePath?: never } | 
/**  macOS bundle ID (e.g., "com.apple.Safari") */
({ BundleId: string }) & { ExecutableName?: never; ExecutablePath?: never; WindowTitle?: never };

export type AppRule = {
	id: string,
	match_type: AppMatchType,
	enabled: boolean,
};

/**  A named collection of blocking rules. */
export type BlockList = {
	id: string,
	name: string,
	enabled: boolean,
	websites: WebsiteRule[],
	applications: AppRule[],
	exceptions: ExceptionRule[],
	lock: Lock | null,
	protection: Protection | null,
	schedule: Schedule | null,
	breaks: BreakConfig | null,
	created_at: string,
	updated_at: string,
};

export type BreakConfig = 
/**  Pomodoro-style: work for X minutes, break for Y minutes. */
({ Pomodoro: {
	work_minutes: number,
	break_minutes: number,
	long_break_minutes: number,
	sessions_before_long_break: number,
} }) & { Allowance?: never } | 
/**  Allowance: X minutes of access per day/hour, tracked by activity. */
({ Allowance: {
	allowed_minutes: number,
	period: AllowancePeriod,
	/**  If true, only counts time when the blocked site/app is in focus. */
	track_active_only: boolean,
} }) & { Pomodoro?: never };

/**
 *  One application action.
 * 
 *  Adjacently tagged so the wire form is `{"cmd": "...", "args": {...}}` — stable,
 *  self-describing, and a clean discriminated union in TypeScript.
 */
export type Command = 
/**  All block lists, with their rules. */
{ cmd: "list_block_lists" } | 
/**  Create an empty block list. Returns the created list. */
{ cmd: "create_block_list"; args: {
	name: string,
} } | 
/**
 *  Replace a block list wholesale.
 * 
 *  Takes a real [`BlockList`], not the JSON string the old
 *  `update_block_list(list_json: String)` accepted.
 */
{ cmd: "update_block_list"; args: {
	list: BlockList,
} } | 
/**  Delete a block list and re-sync the hosts file. */
{ cmd: "delete_block_list"; args: {
	id: string,
} } | 
/**  Enable or disable a block list. */
{ cmd: "toggle_block_list"; args: {
	id: string,
	enabled: boolean,
} };

/**
 *  The wire form of a failure: `{ "code": ..., "message": ... }`.
 * 
 *  A separate type because [`CommandError`] cannot itself derive `specta::Type` —
 *  its `Core` variant wraps `FocuserError`, which has no TypeScript
 *  representation. This is what crosses the boundary, and what the generated
 *  bindings describe.
 */
export type CommandErrorPayload = {
	/**  Stable identifier for the failure kind. Safe to branch on. */
	code: string,
	/**  Human-readable explanation. Not stable; never branch on it. */
	message: string,
};

/**
 *  The result of a successful [`Command`].
 * 
 *  Deliberately typed — the old command layer returned `serde_json::Value` from
 *  24 of its 55 commands, which meant the frontend hand-decoded shapes that the
 *  compiler never checked.
 */
export type CommandResult = 
/**  Succeeded, nothing to return. */
{ kind: "unit" } | { kind: "block_list"; data: BlockList } | { kind: "block_lists"; data: BlockList[] };

export type ExceptionRule = {
	id: string,
	exception_type: ExceptionType,
	enabled: boolean,
};

export type ExceptionType = 
/**  Allow a specific domain even when other rules would block it */
({ Domain: string }) & { Wildcard?: never } | 
/**  Allow a wildcard pattern */
({ Wildcard: string }) & { Domain?: never } | 
/**  Allow local file:// URLs */
"LocalFiles";

/**  How a block is enforced — determines what it takes to disable it. */
export type Lock = 
/**  Block runs for a fixed duration, cannot be cancelled. */
({ Timer: {
	duration_minutes: number,
	started_at: string | null,
} }) & { Password?: never; RandomText?: never; Until?: never } | 
/**  Must type a long random string to unlock. */
({ RandomText: {
	length: number,
} }) & { Password?: never; Timer?: never; Until?: never } | 
/**  Locked until a specific time. */
({ Until: {
	unlock_at: string,
} }) & { Password?: never; RandomText?: never; Timer?: never } | 
/**  Requires system restart to disable (block re-enables on boot). */
"Restart" | 
/**  Password-protected (hashed). */
({ Password: {
	hash: string,
} }) & { RandomText?: never; Timer?: never; Until?: never } | 
/**  Follows the attached schedule — active during scheduled times. */
"Scheduled";

export type Protection = {
	prevent_uninstall: boolean,
	prevent_service_stop: boolean,
	prevent_modification: boolean,
	started_at: string,
	expires_at: string,
};

/**  Weekly recurring schedule. */
export type Schedule = {
	id: string,
	name: string,
	time_slots: TimeSlot[],
	enabled: boolean,
};

/**  A time range on a specific day of the week. */
export type TimeSlot = {
	day: string,
	start: string,
	end: string,
};

/**  How a website rule matches URLs/domains. */
export type WebsiteMatchType = 
/**  Exact domain match (e.g., "reddit.com" blocks reddit.com and *.reddit.com) */
({ Domain: string }) & { Keyword?: never; UrlPath?: never; Wildcard?: never } | 
/**  Wildcard pattern (e.g., "*.social.*") */
({ Wildcard: string }) & { Domain?: never; Keyword?: never; UrlPath?: never } | 
/**  Keyword anywhere in URL (e.g., "game" blocks any URL containing "game") */
({ Keyword: string }) & { Domain?: never; UrlPath?: never; Wildcard?: never } | 
/**  Exact URL path match (e.g., "reddit.com/r/gaming") */
({ UrlPath: string }) & { Domain?: never; Keyword?: never; Wildcard?: never } | 
/**  Block the entire internet (with exceptions only) */
"EntireInternet";

export type WebsiteRule = {
	id: string,
	match_type: WebsiteMatchType,
	enabled: boolean,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

